homepage/urls.py
from django.urls import path
from . import views

app_name= 'homepage'

urlpatterns = [
    path('', views.index, name='home'),
]

ppw_story_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story_6/', include('story_6.urls')),
    path('story_7/', include('story_7.urls')),
    path('story_8/', include('story_8.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('story_9.urls')),
    path('', include('homepage.urls'))
]

story_6/urls.py
from django.urls import path
from . import views

app_name= 'story_6'

urlpatterns = [
    path('', views.index, name='index'),
    path('tambah_aktivitas/', views.tambah_aktivitas, name='tambah_aktivitas'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('tambah_member/', views.tambah_member, name='tambah_member'),
    path('hapus_member/<int:pk>', views.hapus_member, name='hapus_member'),
    path('hapus_aktivitas/<int:pk>', views.hapus_aktivitas, name='hapus_aktivitas')
]

story_7/urls.py
from django.urls import path
from . import views

app_name= 'story_7'

urlpatterns = [
    path('', views.index, name='story_7'),
]

story_8/urls.py
from django.urls import path
from . import views

app_name= 'story_8'

urlpatterns = [
    path('', views.index, name='story_8'),
    path('search/<str:query>/', views.search_book, name='search'),
    path('post/', views.post_like_data, name='post')
]

story_9/urls.py
from django.urls import path
from . import views

app_name= 'story_9'

urlpatterns = [
    path('signup/', views.sign_up_page, name='signup'),
]

homepage/models.py
from django.db import models

# Create your models here.

story_6/models.py
from django.db import models
import datetime

# Create your models here.
class Aktifitas(models.Model):
    deskripsi = models.TextField(max_length=500)
    nama_aktivitas = models.CharField(max_length=200)

    def __str__(self):
        return f"Aktifitas: {self.nama_aktivitas}"


class Member(models.Model):
    aktivitas = models.ManyToManyField(Aktifitas, related_name="member_aktivitas")
    nama_depan_member = models.CharField(max_length=100)
    nama_belakang_member = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.nama_depan_member} {self.nama_belakang_member}"

story_7/models.py
from django.db import models

# Create your models here.

story_8/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    book_id= models.CharField(max_length=200)
    book_title= models.CharField(max_length=200)
    book_author= models.CharField(max_length=200)
    book_publisher= models.CharField(max_length=200)
    book_publishedDate= models.CharField(max_length=200)
    book_rating= models.CharField(max_length=200)
    book_image= models.CharField(max_length=200)
    book_description= models.CharField(max_length=200)
    book_link= models.CharField(max_length=200)
    number_of_likes = models.IntegerField()
    def __str__(self) -> str:
        return f"{self.book_title}"

story_9/models.py
from django.db import models

# Create your models here.

story_6/forms.py
from django import forms
from .models import Aktifitas, Member

class AktifitasForm(forms.ModelForm):

    class Meta:
        model = Aktifitas
        fields = '__all__'

class MemberForm(forms.ModelForm):

    class Meta:
        model = Member
        fields = '__all__'

story_9/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'password1', 'password2']

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'homepage/index.html')

story_6/views.py
from .forms import AktifitasForm, MemberForm
from .models import Aktifitas, Member
from django.shortcuts import redirect, render
from django.contrib import messages

# Create your views here.
def index(request):
    activities = Aktifitas.objects.all()
    return render(request, 'story_6/index.html', {
        "activities" : activities
    })


def tambah_aktivitas(request):
    if request.method == "POST":
        form = AktifitasForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, (f"Aktivitas {request.POST['nama_aktivitas']} berhasil ditambahkan!"))
            return redirect('story_6:index')
    else:
        form = AktifitasForm()
        return render(request, 'story_6/tambah_aktivitas.html', {
            'form': form
        })

def detail(request, pk):
    aktivitas = Aktifitas.objects.get(pk=pk)
    members = Member.objects.filter(aktivitas=aktivitas)
    return render(request, 'story_6/detail.html', {
        'aktivitas': aktivitas, 
        'members': members,
    }) 

def tambah_member(request):
    if request.method == "POST":
        form = MemberForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, (f"{request.POST['nama_depan_member']} {request.POST['nama_belakang_member']} sudah ditambahkan ke aktivitas!"))
            return redirect('story_6:index')
    else:
        form = MemberForm()
        return render(request, 'story_6/tambah_member.html', {
            'form': form
        })

def hapus_member(request, pk):
    member = Member.objects.get(pk=pk)
    messages.success(request, (f"Member {member.nama_depan_member} {member.nama_belakang_member} sudah dihapus!"))
    member.delete()
    return redirect('story_6:index')

def hapus_aktivitas(request, pk):
    aktivitas = Aktifitas.objects.get(pk=pk)
    messages.success(request, (f"Aktivitas {aktivitas.nama_aktivitas} sudah dihapus!"))
    aktivitas.delete()
    return redirect('story_6:index')

story_7/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story_7/index.html')

story_8/views.py
from story_8.models import Book
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
import requests

# Create your views here.
def index(request):
    return render(request, 'story_8/index.html')

def search_book(request, query):
    API_LINK = "https://www.googleapis.com/books/v1/volumes?q=" + query
    data = requests.get(API_LINK).json()
    return JsonResponse(data)

def post_like_data(request):
    if request.method == "POST":
        book_id = request.POST['id']
        try:
            book = Book.objects.get(book_id = book_id)
            num_of_likes = book.number_of_likes
            num_of_likes += 1
            book.number_of_likes = num_of_likes
            book.save()
        except Exception as ex:
            Book.objects.create(
                book_id = request.POST['id'],
                book_title = request.POST['title'],
                book_author = request.POST['author'],
                book_publisher = request.POST['publisher'],
                book_publishedDate = request.POST['publishedDate'],
                book_rating = request.POST['rating'],
                book_image = request.POST['image'],
                book_description = request.POST['description'],
                book_link = request.POST['link'],
                number_of_likes = 1,
            )
    return redirect("story_8:story_8")

story_9/views.py
from story_9.forms import CreateUserForm
from django.shortcuts import redirect, render

# Create your views here.
def sign_up_page(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get("username")
            return redirect('login')
    context = {'form':form}
    return render(request, 'story_9/signup.html', context)

homepage/templates/homepage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block css %}{% endblock css %}
    <link rel="shortcut icon" href="{% static 'homepage/analytics.ico' %}">
    <title>Homepage</title>
</head>
<body>
    {% block content %}{% endblock content %}
    <script src="{% static 'homepage/js/script.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <script>
        // Wrap every letter in a span
            let textWrapper = document.querySelector('.typewritter');
            textWrapper.innerHTML = textWrapper.textContent.replace(/\S/g, "<span class='letter'>$&</span>");

            anime.timeline({ loop: true })
                .add({
                    targets: '.typewritter .letter',
                    scale: [4, 1],
                    opacity: [0, 1],
                    translateZ: 0,
                    easing: "easeOutExpo",
                    duration: 950,
                    delay: (el, i) => 70 * i
                }).add({
                    targets: 'typewritter',
                    opacity: 0,
                    duration: 1000,
                    easing: "easeOutExpo",
                    delay: 1000
                });
    </script>
</body>
</html>

homepage/templates/homepage/index.html
{% extends 'homepage/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'homepage/css/styles.css' %}">{% endblock css %}
{% block content %}

<div class="container my-4">
    {% if user.is_authenticated %}
    <div >
        <h1 class="display-5 text-white typewritter">Halo {{user.username}}...</h1>
    </div>
    <div class="row">
        <a href="{% url 'story_6:index' %}" class="col-6 col-sm-6 col-md-6 col-xl-4 my-3 mx-auto">
            <div class="d-flex align-items-center justify-content-center h2 block">
                <p>Story 6</p>
            </div>
        </a>
        <a href="{% url 'story_7:story_7' %}" class="col-6 col-sm-6 col-md-6 col-xl-4 my-3 mx-auto">
            <div class="d-flex align-items-center justify-content-center h2 block">
                <p>Story 7</p>
            </div>
        </a>
        <a href="{% url 'story_8:story_8' %}" class="col-6 col-sm-6 col-md-6 col-xl-4 my-3 mx-auto">
            <div class="d-flex align-items-center justify-content-center h2 block">
                <p>Story 8</p>
            </div>
        </a>
        <a href="{% url 'login' %}" class="col-6 col-sm-6 col-md-6 col-xl-4 my-3 mx-auto">
            <div class="d-flex align-items-center justify-content-center h2 block">
                <p>Story 9</p>
            </div>
        </a>
        <a href="" class="col-6 col-sm-6 col-md-6 col-xl-4 my-3 mx-auto">
            <div class="d-flex align-items-center justify-content-center h2 block">
                <p>Story 10</p>
            </div>
        </a>
        <a href="" class="col-6 col-md-6 col-xl-4 my-3 mx-auto">
            <div class="d-flex align-items-center justify-content-center h2 block">
                <p>Story Lama</p>
            </div>
        </a>
    </div>
    {% else %}
    <div>
        <h1 class="display-5 text-white typewritter">Halo new visitor...</h1>
        <p class="lead text-white">Silahkan login untuk mendapatkan pengalaman terbaik...</p>
    </div>
    <div class="row">
        <a href="{% url 'login' %}" class="col-6 col-sm-6 col-md-6 col-xl-4 my-3 mx-auto">
            <div class="d-flex align-items-center justify-content-center h2 block">
                <p>Story 6</p>
            </div>
        </a>
        <a href="{% url 'login' %}" class="col-6 col-sm-6 col-md-6 col-xl-4 my-3 mx-auto">
            <div class="d-flex align-items-center justify-content-center h2 block">
                <p>Story 7</p>
            </div>
        </a>
        <a href="{% url 'login' %}" class="col-6 col-sm-6 col-md-6 col-xl-4 my-3 mx-auto">
            <div class="d-flex align-items-center justify-content-center h2 block">
                <p>Story 8</p>
            </div>
        </a>
        <a href="{% url 'login' %}" class="col-6 col-sm-6 col-md-6 col-xl-4 my-3 mx-auto">
            <div class="d-flex align-items-center justify-content-center h2 block">
                <p>Story 9</p>
            </div>
        </a>
        <a href="" class="col-6 col-sm-6 col-md-6 col-xl-4 my-3 mx-auto">
            <div class="d-flex align-items-center justify-content-center h2 block">
                <p>Story 10</p>
            </div>
        </a>
        <a href="" class="col-6 col-md-6 col-xl-4 my-3 mx-auto">
            <div class="d-flex align-items-center justify-content-center h2 block">
                <p>Story Lama</p>
            </div>
        </a>
    </div>
    {% endif %}
</div>

{% endblock content %}

story_6/templates/story_6/detail.html
{% extends 'story_6/layout.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center info my-4">
                <h1 class="font-weight-bold">{{aktivitas}}</h1>
                <p>{{aktivitas.deskripsi}}</p>
                <hr>
            </div>
        </div>
        <h4>Belum daftar? coba <a href="{% url 'story_6:tambah_member' %}">Daftar member</a></h3>
    </div>
    <div class='container'>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Full Name</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for member in members %}
                    <tr>
                        <td>{{member.nama_depan_member}}</td>
                        <td>{{member.nama_belakang_member}}</td>
                        <td>{{member.nama_depan_member}} {{member.nama_belakang_member}}</td>
                        <td><a class="btn btn-danger btn-xl " href="{% url 'story_6:hapus_member' member.id %}">Hapus</a></td>
                    </tr>
                {% empty %}
                    <tr>
                        <th scope="row">-</th>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock  %}

story_6/templates/story_6/index.html
{% extends 'story_6/layout.html' %}
{% block content %}
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center info my-4">
                    <h1 class="font-weight-bold">Daftar Aktifitas</h1>
                    <hr>
                </div>
            </div>
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}
        </div>

        <div class="container">
            <div class="row">
            {% for activity in activities %}
                <div class="col-12 col-md-6 col-xl-4 my-3">
                    <div class="d-flex align-items-center justify-content-center h2 block">
                        <p>{{activity.nama_aktivitas}}</p>
                    </div>
                    <div class="col-md-12 text-center">
                        <a class="btn btn-primary btn-xl" href="{% url 'story_6:detail' activity.id %}">Lihat</a>
                        <a class="btn btn-warning btn-xl " href="{% url 'story_6:hapus_aktivitas' activity.id %}">Hapus</a>
                    </div>
                </div>
                {% empty %}
                    <div class="col-12 col-md-6 col-xl-4 mx-auto">
                        <div class="d-flex align-items-center justify-content-center h2 block">
                            Belum ada aktivitas
                        </div>
                    </div>
                    <div class="col-md-12 text-center">
                        <a class="btn btn-primary btn-xl " href="{% url 'story_6:tambah_aktivitas' %}">Tambah Aktivitas</a>
                    </div>
            {% endfor %}
            </div>
        </div>     
    </section>
{% endblock  %}

story_6/templates/story_6/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'story_6/styles.css' %}">
    <title>My Activities</title>
</head>
<body>
    {% block header %}
        {% include 'story_6/navbar.html' %}
    {% endblock  %}
    
    {% block content %}
    {% endblock  %}

    <!--Javascript from Bootsrap-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>

story_6/templates/story_6/navbar.html
{% load static %}
{% block header %}
{% endblock  %}
<header>
    <nav class="navbar navbar-expand-lg navbar-light scrolling-navbar">
        <div class="container">
            <!--Navbar brand-->
            <a class="navbar-brand font-weight-bold" href="{% url 'story_6:index' %}">Home</a>

            <!--Collapse button if we shrink to smaller screen-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="basicExampleNav">

                <!-- Links -->
                <ul class="navbar-nav ml-auto smooth-scroll">
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="{% url 'story_6:tambah_aktivitas' %}">Tambah Aktifitas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="{% url 'story_6:index' %}">Lihat Aktifitas</a>
                    </li>
                </ul>
            </div>        
        </div>    
    </nav>
</header>

story_6/templates/story_6/tambah_aktivitas.html
{% extends 'story_6/layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center info mb-3 mt-3">
                    <h1 class="font-weight-bold">Aktifitas</h1>
                    <hr>
                </div>
            </div>
            <form method="post">
                {% comment %} tambah csrf_token untuk keamanan  {% endcomment %}
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Simpan</button>
            </form>
        </div>
    </section>
{% endblock  %}

story_6/templates/story_6/tambah_member.html
{% extends 'story_6/layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center info mb-3 mt-3">
                    <h1 class="font-weight-bold">Member</h1>
                    <hr>
                </div>
            </div>
            <form method="post">
                {% comment %} tambah csrf_token untuk keamanan  {% endcomment %}
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Simpan</button>
            </form>
        </div>
    </section>
{% endblock  %}

story_7/templates/story_7/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% block css %}{% endblock css %}
    <link rel="shortcut icon" href="{% static 'story_7/accordion.ico' %}">
    <title>Story {% block title %}{% endblock title %} Daniel</title>
</head>
<body>
    {% block content %}{% endblock content %} 
    <script src="{% static 'story_7/js/script.js' %}"></script>
</body>
</html>

story_7/templates/story_7/index.html
{% extends 'story_7/base.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static 'story_7/css/styles.css' %}">{% endblock css %}
{% block title %}7{% endblock title %}
{% block content %}

    <h1 class="my-4">FAQ</h1>

    <div class="accordion d-flex flex-column">
        <div class="accordion-item accordion-1">
            <div class="accordion-header d-flex justify-content-between align-items-center">
                <p class="accordion-title">Bisa jelaskan deskripsi singkat tentangmu?</p>
                <div class="button-group d-flex justify-content-end justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>

                </div>
            </div>
            <div class="accordion-content">
                <p>Hallo, nama saya Daniel Syahputra, sekarang sedang berkuliah di Fakultas Ilmu Komputer Universitas Indonesia</p>
            </div>
        </div>

        <!-- Items 2 -->
        <div class="accordion-item accordion-2">
            <div class="accordion-header d-flex justify-content-between align-items-center">
                <p class="accordion-title">Aktivitas dan rutinitas saat ini apa saja?</p>
                <div class="button-group d-flex justify-content-end justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="accordion-content">
                <p>
                    Untuk saat ini saya sedang menjalani rutinitas perkuliahan. Namun ada beberapa hal yang saat ini secara rutin saya kerjakan, yaitu:
                </p>
                <ul>
                    <li>
                        Mencoba mengeksplorasi lebih dalam mengenai <strong>web development</strong>
                    </li>
                    <li>
                        Mengasah kemampuan <strong>problem solving</strong> lewat belajar <strong>data structure and algorithm</strong>
                    </li>
                </ul>
            </div>
        </div>

        <div class="accordion-item accordion-3">
            <div class="accordion-header d-flex justify-content-between align-items-center">
                <p class="accordion-title">Tolong ceritakan dong tentang pencapaianmu</p>
                <div class="button-group d-flex justify-content-end justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="accordion-content">
                <p>
                    Menjadi mahasiswa Fasilkom UI
                </p>
            </div>
        </div>

        <div class="accordion-item accordion-4">
            <div class="accordion-header d-flex justify-content-between align-items-center">
                <p class="accordion-title">Kira-kira apa target mu kedepannya?</p>
                <div class="button-group d-flex justify-content-end justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="accordion-content">
                <p>
                    Beberapa target saya kedepannya yaitu:
                </p>
                <ul>
                    <li>Menambah <strong><em>personal / group project</em></strong></li>
                    <li>Meningkatkan kemampuan programming, khususnya kemampuan struktur data dan algoritma</li>
                    <li>Meningkatkan <strong><em>soft skill</em></strong></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

story_8/templates/story_8/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="images" content="{% static 'story_8/images/' %}">
    <meta name="csrf" content="{{ csrf_token }}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% block css %}{% endblock css %}
    <link rel="shortcut icon" href="{% static 'story_8/images/book.ico' %}">
    <title>Story {% block title %}{% endblock title %} Daniel</title>
</head>
<body>
    {% block content %}{% endblock content %}
    <script src="{% static 'story_8/js/script.js' %}"></script>
</body>
</html>

story_8/templates/story_8/index.html
{% extends 'story_8/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'story_8/css/styles.css' %}">
{% endblock css %}
{% block title %}8{% endblock title %}
{% block content %}

    <h1 class="my-4">Book Catalog</h1>

    <!-- Input form -->
    <div class="container">

        <blockquote class="blockquote text-center my-4">
            <p class="mb-0">Anyone who says they have only one life to live must not know how to read a book.</p>
            <footer class="blockquote-footer">Author Unknown</cite></footer>
        </blockquote>

        <div class="input-group mb-3">
            <input id="search-book" type="text" class="form-control" placeholder="Search Book" name="q">
            <div class="input-group-append">
                <button id="button-search" type="button" class="btn btn-outline-success">Success</button>
            </div>
        </div>
    </div>

    <!-- Catalog books -->
    <div class="container" id="display-book">
        
    </div>
    
    
{% endblock content %}

story_9/templates/story_9/signup.html
{% extends 'story_9/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block css %}
<link rel="stylesheet" href="{% static 'story_9/css/styles.css' %}">
{% endblock css %}
{% block title %}Sign Up{% endblock title %}
{% block content %}
<div class="container">
    <div class="row content">
        <div class="col-md-6 mb-3">
            <img src="{% static 'story_9/images/2859735.jpg' %}" class="img-fluid" alt="image">
        </div>
        <div class="col-md-6">
            <h4 class="login-text mb-4">Create a new account</h4>
            <form method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-class">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}